// flow-typed signature: 65bc09cc767bd35c26f84d8a37a0d594
// flow-typed version: <<STUB>>/@loadable/component_v^5.2.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@loadable/component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@loadable/component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@loadable/component/dist/loadable.cjs' {
  declare module.exports: any;
}

declare module '@loadable/component/dist/loadable.es' {
  declare module.exports: any;
}

declare module '@loadable/component/dist/loadable' {
  declare module.exports: any;
}

declare module '@loadable/component/dist/loadable.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@loadable/component/dist/loadable.cjs.js' {
  declare module.exports: $Exports<'@loadable/component/dist/loadable.cjs'>;
}
declare module '@loadable/component/dist/loadable.es.js' {
  declare module.exports: $Exports<'@loadable/component/dist/loadable.es'>;
}
declare module '@loadable/component/dist/loadable.js' {
  declare module.exports: $Exports<'@loadable/component/dist/loadable'>;
}
declare module '@loadable/component/dist/loadable.min.js' {
  declare module.exports: $Exports<'@loadable/component/dist/loadable.min'>;
}
